### ISSUE TITLE
Allow multiple registers to be written at one time

### ISSUE THREAD

**Issue by ajaywazir** [BiancoRoyal/node-red-contrib-modbus-flex-server#5]
### Describe the requested feature

In the following code snippet, if I use  'value': [233,234,235,233],  only first 2 bytes are written.
Ideally it should have written all 4bytes into 2 registers. But this does not happen. 
`msg.payload = {
    //'value': [233,234,235,233], 
    'value': 1234, 
    'register': 'holding', 
    'address': 0 , 
    'disableMsgOutput' : 0 
}; 
return msg;
`

### Motivation

If we design protocol converters using node-red and I receive a IEEE754 float, I cannot write directly to the FlexModbus Server.
I have to split it into two messages.

**Comment by grewek** [comment]
Hello,

So if i understand you correctly you want to write a Holding Register in Bytes?

i.e.

```
[RegisterA_HighByte, RegisterA_LowByte, RegisterB_HighByte, RegisterB_LowByte]
```
